sudo: required 
services:
 - docker
 
 before_install:
  - docker build -t rarzola/react-test -f ./client/Dockerfile.dev ./client
  
 script:
  - docker run -e CI=true rarzola/react-test npm test
  
 after_success:
  - docker build -t rarzola/multi-client ./client
  - docker build -t rarzola/multi-nginx ./nginx
  - docker build -t rarzola/multi-server ./server
  - docker build -t rarzola/multi-worker ./worker
  # Login to the docker CLI
  
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  
  # Take those images and push them to docker hub
  - docker push rarzola/multi-client
  - docker push rarzola/multi-nginx
  - docker push rarzola/multi-server
  - docker push rarzola/multi-worker